### ISSUE TITLE
Would you like to take the lead to https://github.com/Ynn/sd-webui-faceswap

### ISSUE THREAD

**Issue by Ynn** [yownas/sd-webui-faceswapper#2]
I have developed a similar extension that i do not plan to maintain in the future. I have noticed that yours only recently. Would you like to restart from it. I could ask the automatic 1111 community to switch to your version of the extension ?

**Comment by yownas** [comment]
lol
I found your repo a couple of days ago and was thinking about doing the same and link to yours. :)
I wasn't really planning to work much on my version, it is just a minimal implementation to see if it would work at all. (And to be honest I wasn't going to release it first, just uploaded it to make it easier for me to install and hope that someone else would find it and make a "real" extension of it.)

If you really plan to drop your project, I'm ok with you linking to this one. But I can't promise I'll do much more than the current version.

**Comment by Ynn** [comment]
roop has provided another option :)
