### ISSUE TITLE
 After installing it, it downloads some business, but it does not appear in the main menu

### ISSUE THREAD

**Issue by Flickarus** [yownas/sd-webui-faceswapper#4]
![image](https://github.com/yownas/sd-webui-faceswapper/assets/135761968/384cad78-9131-43c6-adae-d58b8a341e15)

**Comment by yownas** [comment]
I'm using the same library as https://github.com/s0md3v/sd-webui-roop, and they talk about needing to install [Visual Studio](https://visualstudio.microsoft.com/downloads/).

```
On Windows, download and install [Visual Studio](https://visualstudio.microsoft.com/downloads/). During the install, make sure to include the Python and C++ packages.
```

I'm using Linux so I never had to do that...but if you install Visual Studio, I think it should start. While you are there, you can also download the [inswapper_128.onnx](https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx)  and place it in the sd-webui-faceswapper folder.
